//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakeOutAdmin.SrvAdmin {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SrvAdmin.IFoodOrder", CallbackContract=typeof(TakeOutAdmin.SrvAdmin.IFoodOrderCallback))]
    public interface IFoodOrder {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFoodOrder/GetOderNumber", ReplyAction="http://tempuri.org/IFoodOrder/GetOderNumberResponse")]
        int GetOderNumber();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFoodOrder/GetOderNumber", ReplyAction="http://tempuri.org/IFoodOrder/GetOderNumberResponse")]
        System.Threading.Tasks.Task<int> GetOderNumberAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFoodOrder/GetProductList", ReplyAction="http://tempuri.org/IFoodOrder/GetProductListResponse")]
        FastFoodService.Product[] GetProductList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFoodOrder/GetProductList", ReplyAction="http://tempuri.org/IFoodOrder/GetProductListResponse")]
        System.Threading.Tasks.Task<FastFoodService.Product[]> GetProductListAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IFoodOrder/CreateOrder")]
        void CreateOrder(string[] list, int orderNr);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IFoodOrder/CreateOrder")]
        System.Threading.Tasks.Task CreateOrderAsync(string[] list, int orderNr);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFoodOrderCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFoodOrder/OrderStatus", ReplyAction="http://tempuri.org/IFoodOrder/OrderStatusResponse")]
        void OrderStatus(bool status, string message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFoodOrderChannel : TakeOutAdmin.SrvAdmin.IFoodOrder, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FoodOrderClient : System.ServiceModel.DuplexClientBase<TakeOutAdmin.SrvAdmin.IFoodOrder>, TakeOutAdmin.SrvAdmin.IFoodOrder {
        
        public FoodOrderClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public FoodOrderClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public FoodOrderClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public FoodOrderClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public FoodOrderClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public int GetOderNumber() {
            return base.Channel.GetOderNumber();
        }
        
        public System.Threading.Tasks.Task<int> GetOderNumberAsync() {
            return base.Channel.GetOderNumberAsync();
        }
        
        public FastFoodService.Product[] GetProductList() {
            return base.Channel.GetProductList();
        }
        
        public System.Threading.Tasks.Task<FastFoodService.Product[]> GetProductListAsync() {
            return base.Channel.GetProductListAsync();
        }
        
        public void CreateOrder(string[] list, int orderNr) {
            base.Channel.CreateOrder(list, orderNr);
        }
        
        public System.Threading.Tasks.Task CreateOrderAsync(string[] list, int orderNr) {
            return base.Channel.CreateOrderAsync(list, orderNr);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SrvAdmin.IFoodAdmin", CallbackContract=typeof(TakeOutAdmin.SrvAdmin.IFoodAdminCallback))]
    public interface IFoodAdmin {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFoodAdmin/Connect", ReplyAction="http://tempuri.org/IFoodAdmin/ConnectResponse")]
        void Connect();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFoodAdmin/Connect", ReplyAction="http://tempuri.org/IFoodAdmin/ConnectResponse")]
        System.Threading.Tasks.Task ConnectAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFoodAdmin/Disconnect", ReplyAction="http://tempuri.org/IFoodAdmin/DisconnectResponse")]
        void Disconnect();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFoodAdmin/Disconnect", ReplyAction="http://tempuri.org/IFoodAdmin/DisconnectResponse")]
        System.Threading.Tasks.Task DisconnectAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IFoodAdmin/DeliverOrder")]
        void DeliverOrder(int orderNr);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IFoodAdmin/DeliverOrder")]
        System.Threading.Tasks.Task DeliverOrderAsync(int orderNr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFoodAdmin/GetOrders", ReplyAction="http://tempuri.org/IFoodAdmin/GetOrdersResponse")]
        int[] GetOrders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFoodAdmin/GetOrders", ReplyAction="http://tempuri.org/IFoodAdmin/GetOrdersResponse")]
        System.Threading.Tasks.Task<int[]> GetOrdersAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFoodAdminCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IFoodAdmin/NewOrder")]
        void NewOrder(int orderNr);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IFoodAdmin/OrderDelivered")]
        void OrderDelivered(int orderNr);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFoodAdminChannel : TakeOutAdmin.SrvAdmin.IFoodAdmin, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FoodAdminClient : System.ServiceModel.DuplexClientBase<TakeOutAdmin.SrvAdmin.IFoodAdmin>, TakeOutAdmin.SrvAdmin.IFoodAdmin {
        
        public FoodAdminClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public FoodAdminClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public FoodAdminClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public FoodAdminClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public FoodAdminClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Connect() {
            base.Channel.Connect();
        }
        
        public System.Threading.Tasks.Task ConnectAsync() {
            return base.Channel.ConnectAsync();
        }
        
        public void Disconnect() {
            base.Channel.Disconnect();
        }
        
        public System.Threading.Tasks.Task DisconnectAsync() {
            return base.Channel.DisconnectAsync();
        }
        
        public void DeliverOrder(int orderNr) {
            base.Channel.DeliverOrder(orderNr);
        }
        
        public System.Threading.Tasks.Task DeliverOrderAsync(int orderNr) {
            return base.Channel.DeliverOrderAsync(orderNr);
        }
        
        public int[] GetOrders() {
            return base.Channel.GetOrders();
        }
        
        public System.Threading.Tasks.Task<int[]> GetOrdersAsync() {
            return base.Channel.GetOrdersAsync();
        }
    }
}
